apiVersion: litmuchaos.io/v1alpha1
kind: ChartServiceVersion
metadata:
  createdAt: 2021-04-04T13:41:08Z
  name: djin-shared-test
  version: 1.0.0
  annotations:
    categories: app-compute-network-chaos
    chartDescription: Injects chaos on application pods using cmd probe.
spec:
  displayName: djin-shared-test
  categoryDescription: >
    CRONWORKFLOW
  experiments:
    - pod-delete
  keywords:
    - Kubernetes
    - Pod
  platforms:
    - GKE
    - Minikube
    - Packet(Kubeadm)
    - EKS
    - AKS
  maintainers:
    - name: lamc
      email: crystal.lam@dowjones.com
  provider:
    name: ChaosNative
  links:
    - name: PIB Service Mesh Slack
      url: https://app.slack.com/client/T025QN6JG/CBQLJ650T
    - name: Documentation
      url: https://docs.litmuschaos.io/docs/chaoshub/#generic-chaos
  icon:
    - url:
      mediatype: image/png
