apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: app-dns-chaos-workflow-
  namespace: litmus
  labels:
    subject: "app-dns-chaos_{{workflow.parameters.appNamespace}}"
spec:
  arguments:
    parameters:
      - name: adminModeNamespace
        value: litmus
      - name: appNamespace
        value: djin-productivity
  entrypoint: app-dns-chaos
  podGC:
    strategy: OnWorkflowSuccess
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: argo-chaos
  templates:
    - name: app-dns-chaos
      steps:
        - - name: install-chaos-experiments
            template: install-chaos-experiments
        - - name: pod-dns-error
            template: pod-dns-error
        - - name: pod-dns-spoof
            template: pod-dns-spoof
        - - name: revert-chaos
            template: revert-chaos

    - name: install-chaos-experiments
      inputs:
        artifacts:
          - name: pod-dns-error
            path: /tmp/pod-dns-error.yaml
            raw:
              data: |
                apiVersion: litmuschaos.io/v1alpha1
                description:
                  message: |
                    Pod DNS Error injects dns failure/error in target pod containers
                kind: ChaosExperiment
                metadata:
                  name: pod-dns-error
                  labels:
                    name: pod-dns-error
                    app.kubernetes.io/part-of: litmus
                    app.kubernetes.io/component: chaosexperiment
                    app.kubernetes.io/version: latest
                spec:
                  definition:
                    scope: Namespaced
                    permissions:
                      - apiGroups:
                          - ""
                        resources:
                          - pods
                        verbs:
                          - create
                          - delete
                          - get
                          - list
                          - patch
                          - update
                          - deletecollection
                      - apiGroups:
                          - ""
                        resources:
                          - events
                        verbs:
                          - create
                          - get
                          - list
                          - patch
                          - update
                      - apiGroups:
                          - ""
                        resources:
                          - configmaps
                        verbs:
                          - get
                          - list
                      - apiGroups:
                          - ""
                        resources:
                          - pods/log
                        verbs:
                          - get
                          - list
                          - watch
                      - apiGroups:
                          - ""
                        resources:
                          - pods/exec
                        verbs:
                          - get
                          - list
                          - create
                      - apiGroups:
                          - apps
                        resources:
                          - deployments
                          - statefulsets
                          - replicasets
                          - daemonsets
                        verbs:
                          - list
                          - get
                      - apiGroups:
                          - apps.openshift.io
                        resources:
                          - deploymentconfigs
                        verbs:
                          - list
                          - get
                      - apiGroups:
                          - ""
                        resources:
                          - replicationcontrollers
                        verbs:
                          - get
                          - list
                      - apiGroups:
                          - argoproj.io
                        resources:
                          - rollouts
                        verbs:
                          - list
                          - get
                      - apiGroups:
                          - batch
                        resources:
                          - jobs
                        verbs:
                          - create
                          - list
                          - get
                          - delete
                          - deletecollection
                      - apiGroups:
                          - litmuschaos.io
                        resources:
                          - chaosengines
                          - chaosexperiments
                          - chaosresults
                        verbs:
                          - create
                          - list
                          - get
                          - patch
                          - update
                          - delete
                    image: litmuschaos/go-runner:latest
                    args:
                      - -c
                      - ./experiments -name pod-dns-error
                    command:
                      - /bin/bash
                    env:
                      - name: TARGET_CONTAINER
                        value: ""
                      - name: LIB_IMAGE
                        value: litmuschaos/go-runner:latest
                      - name: TOTAL_CHAOS_DURATION
                        value: "60"
                      - name: RAMP_TIME
                        value: ""
                      - name: PODS_AFFECTED_PERC
                        value: ""
                      - name: TARGET_PODS
                        value: ""
                      - name: CONTAINER_RUNTIME
                        value: docker
                      - name: SOCKET_PATH
                        value: /var/run/docker.sock
                      - name: SEQUENCE
                        value: parallel
                      - name: TARGET_HOSTNAMES
                        value: ""
                      - name: MATCH_SCHEME
                        value: exact
                    labels:
                      experiment: pod-dns-error
                      app.kubernetes.io/part-of: litmus
                      app.kubernetes.io/component: experiment-job
                      app.kubernetes.io/runtime-api-usage: "true"
                      app.kubernetes.io/version: latest
          - name: pod-dns-spoof
            path: /tmp/pod-dns-spoof.yaml
            raw:
              data: |
                apiVersion: litmuschaos.io/v1alpha1
                description:
                  message: >
                    Pod DNS Spoof can spoof particular dns requests in target pod container to
                    desired target hostnames
                kind: ChaosExperiment
                metadata:
                  name: pod-dns-spoof
                  labels:
                    name: pod-dns-spoof
                    app.kubernetes.io/part-of: litmus
                    app.kubernetes.io/component: chaosexperiment
                    app.kubernetes.io/version: latest
                spec:
                  definition:
                    scope: Namespaced
                    permissions:
                      - apiGroups:
                          - ""
                        resources:
                          - pods
                        verbs:
                          - create
                          - delete
                          - get
                          - list
                          - patch
                          - update
                          - deletecollection
                      - apiGroups:
                          - ""
                        resources:
                          - events
                        verbs:
                          - create
                          - get
                          - list
                          - patch
                          - update
                      - apiGroups:
                          - ""
                        resources:
                          - configmaps
                        verbs:
                          - get
                          - list
                      - apiGroups:
                          - ""
                        resources:
                          - pods/log
                        verbs:
                          - get
                          - list
                          - watch
                      - apiGroups:
                          - ""
                        resources:
                          - pods/exec
                        verbs:
                          - get
                          - list
                          - create
                      - apiGroups:
                          - apps
                        resources:
                          - deployments
                          - statefulsets
                          - replicasets
                          - daemonsets
                        verbs:
                          - list
                          - get
                      - apiGroups:
                          - apps.openshift.io
                        resources:
                          - deploymentconfigs
                        verbs:
                          - list
                          - get
                      - apiGroups:
                          - ""
                        resources:
                          - replicationcontrollers
                        verbs:
                          - get
                          - list
                      - apiGroups:
                          - argoproj.io
                        resources:
                          - rollouts
                        verbs:
                          - list
                          - get
                      - apiGroups:
                          - batch
                        resources:
                          - jobs
                        verbs:
                          - create
                          - list
                          - get
                          - delete
                          - deletecollection
                      - apiGroups:
                          - litmuschaos.io
                        resources:
                          - chaosengines
                          - chaosexperiments
                          - chaosresults
                        verbs:
                          - create
                          - list
                          - get
                          - patch
                          - update
                          - delete
                    image: litmuschaos/go-runner:latest
                    args:
                      - -c
                      - ./experiments -name pod-dns-spoof
                    command:
                      - /bin/bash
                    env:
                      - name: TARGET_CONTAINER
                        value: ""
                      - name: LIB_IMAGE
                        value: litmuschaos/go-runner:latest
                      - name: TOTAL_CHAOS_DURATION
                        value: "60"
                      - name: RAMP_TIME
                        value: ""
                      - name: PODS_AFFECTED_PERC
                        value: ""
                      - name: TARGET_PODS
                        value: ""
                      - name: CONTAINER_RUNTIME
                        value: docker
                      - name: SOCKET_PATH
                        value: /var/run/docker.sock
                      - name: SEQUENCE
                        value: parallel
                      - name: SPOOF_MAP
                        value: ""
                    labels:
                      experiment: pod-dns-spoof
                      app.kubernetes.io/part-of: litmus
                      app.kubernetes.io/component: experiment-job
                      app.kubernetes.io/runtime-api-usage: "true"
                      app.kubernetes.io/version: latest
      container:
        args:
          - kubectl apply -f /tmp/pod-network-loss.yaml -n {{workflow.parameters.adminModeNamespace}}
            | kubectl apply -f /tmp/pod-network-latency.yaml -n {{workflow.parameters.adminModeNamespace}}
            | kubectl apply -f /tmp/pod-network-corruption.yaml -n {{workflow.parameters.adminModeNamespace}}
            | kubectl apply -f /tmp/pod-network-duplication.yaml -n {{workflow.parameters.adminModeNamespace}}
            | kubectl apply -f /tmp/pod-dns-error.yaml -n {{workflow.parameters.adminModeNamespace}}
            | kubectl apply -f /tmp/pod-dns-spoof.yaml -n {{workflow.parameters.adminModeNamespace}} | sleep 30
        command:
          - sh
          - -c
        image: litmuschaos/k8s:latest

    - name: pod-dns-error
      inputs:
        artifacts:
          - name: pod-dns-error
            path: /tmp/chaosengine-pod-dns-error.yaml
            raw:
              data: |
                apiVersion: litmuschaos.io/v1alpha1
                kind: ChaosEngine
                metadata:
                  name: app-pod-dns-error
                  namespace: "{{workflow.parameters.adminModeNamespace}}"
                  labels:
                    context: "pod-dns-error_{{workflow.parameters.appNamespace}}"
                spec:
                  appinfo:
                    appns: djin-productivity
                    applabel: app=kiali
                    appkind: deployment
                  engineState: active
                  auxiliaryAppInfo: ""
                  chaosServiceAccount: litmus-admin
                  experiments:
                    - name: pod-dns-error
                      spec:
                        components:
                          env:
                            - name: TOTAL_CHAOS_DURATION
                              value: "60"
                            - name: TARGET_HOSTNAMES
                              value: ""
                            - name: MATCH_SCHEME
                              value: exact
                            - name: CONTAINER_RUNTIME
                              value: docker
                            - name: SOCKET_PATH
                              value: /var/run/docker.sock
                            - name: PODS_AFFECTED_PERC
                              value: "100"
                        probe: []
                  annotationCheck: "false"
      container:
        args:
          - -file=/tmp/chaosengine-pod-dns-error.yaml
          - -saveName=/tmp/engine-name
        image: litmuschaos/litmus-checker:latest

    - name: pod-dns-spoof
      inputs:
        artifacts:
          - name: pod-dns-spoof
            path: /tmp/chaosengine-pod-dns-spoof.yaml
            raw:
              data: |
                apiVersion: litmuschaos.io/v1alpha1
                kind: ChaosEngine
                metadata:
                  name: app-pod-dns-spoof
                  namespace: "{{workflow.parameters.adminModeNamespace}}"
                  labels:
                    context: "pod-dns-spoof_{{workflow.parameters.appNamespace}}"
                spec:
                  appinfo:
                    appns: djin-productivity
                    applabel: app=kiali
                    appkind: deployment
                  engineState: active
                  auxiliaryAppInfo: ""
                  chaosServiceAccount: litmus-admin
                  experiments:
                    - name: pod-dns-spoof
                      spec:
                        components:
                          env:
                            - name: TOTAL_CHAOS_DURATION
                              value: "60"
                            - name: SPOOF_MAP
                              value: '{"google.com":"fakegoogle.com"}'
                            - name: CONTAINER_RUNTIME
                              value: docker
                            - name: SOCKET_PATH
                              value: /var/run/docker.sock
                            - name: PODS_AFFECTED_PERC
                              value: "100"
                        probe: []
                  annotationCheck: "false"
      container:
        args:
          - -file=/tmp/chaosengine-pod-dns-spoof.yaml
          - -saveName=/tmp/engine-name
        image: litmuschaos/litmus-checker:latest

    - name: revert-chaos
      container:
        image: litmuschaos/k8s:latest
        command: [sh, -c]
        args:
          [
            "kubectl delete chaosengine app-pod-dns-error app-pod-dns-spoof -n {{workflow.parameters.adminModeNamespace}}"
          ]
